### PR TITLE
Adding phpstan as static analyzer tool

### PR DESCRIPTION
**Pull request by reisraff**

### CODE REVIEW

**Comment by oscarotero** [comment]
Mmm, seems that phpstan is not compatible with php 7.0 https://travis-ci.org/middlewares/access-log/jobs/438651330

**Comment by reisraff** [comment]
There is a way to work around this, and run just in >= 7.1

**Comment by oscarotero** [comment]
If you know how to do it, I'll merge this

**Comment by reisraff** [comment]
@oscarotero done

**Comment by oscarotero** [comment]
Thanks. I'm going to include this change to all other middlewares.

**Comment by reisraff** [comment]
@oscarotero can I do some? for #hacktoberfest

**Comment by oscarotero** [comment]
Don't worry. I have a script to automate changes to all middlewares: If you're curious, this is an early version: https://gist.github.com/oscarotero/635ad936a502b2e6c314d36ef16da5dc

**Comment by oscarotero** [comment]
I edited your changes and now it installs phpstan 0.9 in php7.0 and v0.10 in newer versions.

**Pull request merged**
