### PR TITLE
[WIP] Define commonly used log formats

### PR DESCRIPTION
**Pull request by ajgarlag**
@oscarotero What do you think about this?

### CODE REVIEW

**Comment by oscarotero** [comment]
Yes, I was thinking in something like that. My only concern is overloading the middleware with values that wont be used.

**Comment by ajgarlag** [comment]
That is my opinion too. For example, to compute the %O parameter used by debian formats there is some overhead that should be avoided when not necessary.

**Comment by oscarotero** [comment]
Another approach is something like this: https://github.com/guzzle/guzzle/blob/master/src/MessageFormatter.php that uses `preg_replace_callback` to compute only the needed values.

**Comment by oscarotero** [comment]
Great job. thank you 👍

**Pull request merged**
